# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160828_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=b'', upload_to=b''),
        ),
    ]
